/**
 * Quiz Generator
 *
 * Generates dynamic quiz questions from course content.
 * Questions are derived from the processed JSON — no AI required.
 * In future versions, AI can generate additional questions.
 */

import type { Quiz, Question } from '@/types/quiz'
import { generateUUID } from '@/lib/utils'

// ──────────────────────────────────────────────────
// Curated question banks per course
// (In production, these would be in a database or
//  generated by AI from the course content)
// ──────────────────────────────────────────────────

const QUESTION_BANKS: Record<string, Question[]> = {
    html: [
        {
            id: 'html-1', type: 'single-choice',
            question: 'Which DOCTYPE declaration is correct for HTML5?',
            options: [
                { id: 'a', text: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">', isCorrect: false },
                { id: 'b', text: '<!DOCTYPE html>', isCorrect: true },
                { id: 'c', text: '<html version="5">', isCorrect: false },
                { id: 'd', text: '<?xml version="1.0"?>', isCorrect: false },
            ],
            explanation: '<!DOCTYPE html> is the correct HTML5 DOCTYPE. It tells the browser to render in standards mode.',
            difficulty: 'easy', tags: ['html', 'fundamentals'], points: 1,
        },
        {
            id: 'html-2', type: 'single-choice',
            question: 'Which attribute is REQUIRED on every <img> element?',
            options: [
                { id: 'a', text: 'src only', isCorrect: false },
                { id: 'b', text: 'alt only', isCorrect: false },
                { id: 'c', text: 'Both src and alt', isCorrect: true },
                { id: 'd', text: 'width and height', isCorrect: false },
            ],
            explanation: 'Both src (image source) and alt (alternative text) are required. alt="" is valid for decorative images, but the attribute must be present for accessibility.',
            difficulty: 'easy', tags: ['html', 'accessibility'], points: 1,
        },
        {
            id: 'html-3', type: 'single-choice',
            question: 'What is the correct way to link a label to an input?',
            options: [
                { id: 'a', text: '<label><input> is enough', isCorrect: false },
                { id: 'b', text: 'Using matching for and id attributes', isCorrect: true },
                { id: 'c', text: 'Using aria-label on the input', isCorrect: false },
                { id: 'd', text: 'Placing the label before the input', isCorrect: false },
            ],
            explanation: 'The for attribute on <label> must match the id attribute on <input>. This creates a programmatic association that benefits screen readers and allows clicking the label to focus the input.',
            difficulty: 'medium', tags: ['html', 'forms', 'accessibility'], points: 2,
        },
        {
            id: 'html-4', type: 'multiple-choice',
            question: 'Which of the following are semantic HTML5 elements? (Select all that apply)',
            options: [
                { id: 'a', text: '<div>', isCorrect: false },
                { id: 'b', text: '<article>', isCorrect: true },
                { id: 'c', text: '<section>', isCorrect: true },
                { id: 'd', text: '<nav>', isCorrect: true },
                { id: 'e', text: '<span>', isCorrect: false },
            ],
            explanation: '<article>, <section>, and <nav> are semantic HTML5 elements that convey meaning about their content. <div> and <span> are generic containers with no semantic meaning.',
            difficulty: 'easy', tags: ['html', 'semantic'], points: 2,
        },
        {
            id: 'html-5', type: 'true-false',
            question: 'The <meta name="viewport"> tag is optional for responsive websites.',
            answer: false,
            explanation: 'The viewport meta tag is essential for responsive design. Without it, mobile browsers render pages at desktop width (usually 980px) and scale them down, breaking all responsive CSS.',
            difficulty: 'medium', tags: ['html', 'responsive'], points: 1,
        },
        {
            id: 'html-6', type: 'code-output',
            question: 'What is wrong with this link?',
            code: '<a href="https://example.com" target="_blank">External Site</a>',
            language: 'html',
            options: [
                { id: 'a', text: 'The href is wrong', isCorrect: false },
                { id: 'b', text: 'Missing rel="noopener noreferrer"', isCorrect: true },
                { id: 'c', text: 'target="_blank" is deprecated', isCorrect: false },
                { id: 'd', text: 'Nothing is wrong', isCorrect: false },
            ],
            explanation: 'When using target="_blank", you must add rel="noopener noreferrer" to prevent the opened page from accessing window.opener (reverse tabnapping security vulnerability).',
            difficulty: 'medium', tags: ['html', 'security'], points: 2,
        },
    ],

    css: [
        {
            id: 'css-1', type: 'single-choice',
            question: 'Which box-sizing value makes width include padding and border?',
            options: [
                { id: 'a', text: 'content-box', isCorrect: false },
                { id: 'b', text: 'border-box', isCorrect: true },
                { id: 'c', text: 'padding-box', isCorrect: false },
                { id: 'd', text: 'full-box', isCorrect: false },
            ],
            explanation: 'box-sizing: border-box is the professional standard. It makes width and height include padding and border, making dimensions predictable.',
            difficulty: 'easy', tags: ['css', 'box-model'], points: 1,
        },
        {
            id: 'css-2', type: 'single-choice',
            question: 'Which CSS pseudo-class shows focus indicators only for keyboard navigation (not mouse clicks)?',
            options: [
                { id: 'a', text: ':focus', isCorrect: false },
                { id: 'b', text: ':hover', isCorrect: false },
                { id: 'c', text: ':focus-visible', isCorrect: true },
                { id: 'd', text: ':focus-within', isCorrect: false },
            ],
            explanation: ':focus-visible applies styles only when the browser determines the focus should be visually indicated (keyboard navigation), not when using a mouse. This is the modern accessibility-correct approach.',
            difficulty: 'medium', tags: ['css', 'accessibility'], points: 2,
        },
        {
            id: 'css-3', type: 'code-output',
            question: 'What is the specificity of this selector: .card .card__title',
            code: '.card .card__title { color: red; }',
            language: 'css',
            options: [
                { id: 'a', text: '(0,1,0,0)', isCorrect: false },
                { id: 'b', text: '(0,0,2,0)', isCorrect: true },
                { id: 'c', text: '(0,2,0,0)', isCorrect: false },
                { id: 'd', text: '(0,0,0,2)', isCorrect: false },
            ],
            explanation: 'Two class selectors give a specificity of (0,0,2,0). Classes score (0,0,1,0) each, IDs score (0,1,0,0), and elements score (0,0,0,1).',
            difficulty: 'hard', tags: ['css', 'specificity'], points: 3,
        },
        {
            id: 'css-4', type: 'multiple-choice',
            question: 'Which CSS properties are GPU-composited (best for animations)? (Select all)',
            options: [
                { id: 'a', text: 'transform', isCorrect: true },
                { id: 'b', text: 'opacity', isCorrect: true },
                { id: 'c', text: 'width', isCorrect: false },
                { id: 'd', text: 'height', isCorrect: false },
                { id: 'e', text: 'filter', isCorrect: true },
            ],
            explanation: 'transform, opacity, and filter are composited by the GPU and do not trigger layout or paint recalculations. Animating width or height triggers expensive layout reflows.',
            difficulty: 'hard', tags: ['css', 'performance'], points: 3,
        },
    ],

    javascript: [
        {
            id: 'js-1', type: 'single-choice',
            question: 'What will console.log(typeof null) output?',
            options: [
                { id: 'a', text: '"null"', isCorrect: false },
                { id: 'b', text: '"undefined"', isCorrect: false },
                { id: 'c', text: '"object"', isCorrect: true },
                { id: 'd', text: '"boolean"', isCorrect: false },
            ],
            explanation: 'typeof null returns "object" — this is a well-known JavaScript bug from 1995 that was never fixed for backwards compatibility. Use === null to check for null.',
            difficulty: 'medium', tags: ['javascript', 'types'], points: 2,
        },
        {
            id: 'js-2', type: 'code-output',
            question: 'What is the output order of this code?',
            code: `console.log('1');
setTimeout(() => console.log('2'), 0);
Promise.resolve().then(() => console.log('3'));
console.log('4');`,
            language: 'javascript',
            options: [
                { id: 'a', text: '1, 2, 3, 4', isCorrect: false },
                { id: 'b', text: '1, 4, 3, 2', isCorrect: true },
                { id: 'c', text: '1, 4, 2, 3', isCorrect: false },
                { id: 'd', text: '1, 3, 4, 2', isCorrect: false },
            ],
            explanation: 'Synchronous code runs first (1, 4). Then microtasks (Promises) run before macrotasks (setTimeout). So Promise logs 3 before setTimeout logs 2.',
            difficulty: 'hard', tags: ['javascript', 'event-loop'], points: 3,
        },
        {
            id: 'js-3', type: 'single-choice',
            question: 'Which method creates a SHALLOW copy of an object?',
            options: [
                { id: 'a', text: 'JSON.parse(JSON.stringify(obj))', isCorrect: false },
                { id: 'b', text: 'Object.assign({}, obj)', isCorrect: true },
                { id: 'c', text: 'structuredClone(obj)', isCorrect: false },
                { id: 'd', text: 'obj.clone()', isCorrect: false },
            ],
            explanation: 'Object.assign({}, obj) and {...obj} create shallow copies — nested objects still share references. structuredClone() and JSON.parse/stringify create deep copies.',
            difficulty: 'medium', tags: ['javascript', 'objects'], points: 2,
        },
        {
            id: 'js-4', type: 'true-false',
            question: 'Arrow functions have their own "this" binding.',
            answer: false,
            explanation: 'Arrow functions do NOT have their own "this". They inherit "this" from their enclosing lexical scope. This makes them unsuitable as object methods but ideal as callbacks.',
            difficulty: 'medium', tags: ['javascript', 'this', 'functions'], points: 2,
        },
        {
            id: 'js-5', type: 'multiple-choice',
            question: 'Which are falsy values in JavaScript? (Select all)',
            options: [
                { id: 'a', text: 'false', isCorrect: true },
                { id: 'b', text: '0', isCorrect: true },
                { id: 'c', text: '""', isCorrect: true },
                { id: 'd', text: '[]', isCorrect: false },
                { id: 'e', text: 'null', isCorrect: true },
                { id: 'f', text: '{}', isCorrect: false },
            ],
            explanation: 'Falsy values: false, 0, -0, 0n, "", null, undefined, NaN. Empty arrays ([]) and empty objects ({}) are truthy.',
            difficulty: 'medium', tags: ['javascript', 'types', 'coercion'], points: 2,
        },
    ],

    php: [
        {
            id: 'php-1', type: 'single-choice',
            question: 'Which function should you use to hash passwords in PHP?',
            options: [
                { id: 'a', text: 'md5()', isCorrect: false },
                { id: 'b', text: 'sha1()', isCorrect: false },
                { id: 'c', text: 'password_hash()', isCorrect: true },
                { id: 'd', text: 'hash("sha256", ...)', isCorrect: false },
            ],
            explanation: 'password_hash() uses bcrypt with automatic salting, making rainbow table attacks impossible and brute-force computationally expensive. MD5 and SHA1 are cryptographically broken.',
            difficulty: 'easy', tags: ['php', 'security'], points: 2,
        },
        {
            id: 'php-2', type: 'true-false',
            question: 'PDO prepared statements automatically prevent SQL injection.',
            answer: true,
            explanation: 'PDO prepared statements separate SQL code from data. The database treats bound parameters as pure data, making SQL injection impossible — the attacker\'s payload cannot alter the query structure.',
            difficulty: 'easy', tags: ['php', 'security', 'pdo'], points: 1,
        },
        {
            id: 'php-3', type: 'code-output',
            question: 'What is the output of this PHP code?',
            code: '<?php\n$a = "5";\n$b = 10;\necho $a + $b;',
            language: 'php',
            options: [
                { id: 'a', text: '"510"', isCorrect: false },
                { id: 'b', text: '15', isCorrect: true },
                { id: 'c', text: 'Error', isCorrect: false },
                { id: 'd', text: '"5" + 10', isCorrect: false },
            ],
            explanation: 'PHP performs type coercion in arithmetic operations. The string "5" is converted to the integer 5, so "5" + 10 = 15. This is why declare(strict_types=1) is recommended.',
            difficulty: 'medium', tags: ['php', 'types'], points: 2,
        },
    ],

    laravel: [
        {
            id: 'laravel-1', type: 'single-choice',
            question: 'What is the N+1 query problem in Eloquent?',
            options: [
                { id: 'a', text: 'Running more than N queries per request', isCorrect: false },
                { id: 'b', text: 'Loading N related models with 1 query per model instead of a single JOIN', isCorrect: true },
                { id: 'c', text: 'Having more than 1 database connection', isCorrect: false },
                { id: 'd', text: 'Using N+1 as a query limit', isCorrect: false },
            ],
            explanation: 'N+1 occurs when you load a collection (1 query) then access a relationship on each item (N queries). Fix with eager loading: Model::with(["relationship"])->get()',
            difficulty: 'medium', tags: ['laravel', 'eloquent', 'performance'], points: 2,
        },
        {
            id: 'laravel-2', type: 'single-choice',
            question: 'Where should business logic live in a Laravel application?',
            options: [
                { id: 'a', text: 'In controllers', isCorrect: false },
                { id: 'b', text: 'In Eloquent models', isCorrect: false },
                { id: 'c', text: 'In service classes', isCorrect: true },
                { id: 'd', text: 'In routes', isCorrect: false },
            ],
            explanation: 'Business logic belongs in service classes. Controllers handle HTTP concerns only (receive request, return response). Services are testable, reusable from queues/commands, and not tied to HTTP.',
            difficulty: 'medium', tags: ['laravel', 'architecture'], points: 2,
        },
        {
            id: 'laravel-3', type: 'multiple-choice',
            question: 'Which Artisan commands should be run in production deployment? (Select all)',
            options: [
                { id: 'a', text: 'php artisan optimize', isCorrect: true },
                { id: 'b', text: 'php artisan migrate --force', isCorrect: true },
                { id: 'c', text: 'php artisan tinker', isCorrect: false },
                { id: 'd', text: 'php artisan config:cache', isCorrect: true },
                { id: 'e', text: 'php artisan serve', isCorrect: false },
            ],
            explanation: 'optimize, migrate --force, and config:cache are production deployment commands. tinker is an interactive shell (development only), serve is a development server.',
            difficulty: 'medium', tags: ['laravel', 'deployment'], points: 2,
        },
    ],

    jquery: [
        {
            id: 'jq-1', type: 'single-choice',
            question: 'What is wrong with this event handler for dynamically added elements?',
            options: [
                { id: 'a', text: 'The selector is wrong', isCorrect: false },
                { id: 'b', text: 'It only binds to elements that exist at bind time, not future elements', isCorrect: true },
                { id: 'c', text: '.on() is deprecated', isCorrect: false },
                { id: 'd', text: 'Nothing is wrong', isCorrect: false },
            ],
            explanation: 'Direct binding ($(".card").on("click")) only works on elements existing at bind time. Use event delegation instead: $(staticParent).on("click", ".card", handler) to handle current and future elements.',
            difficulty: 'medium', tags: ['jquery', 'events'], points: 2,
        },
        {
            id: 'jq-2', type: 'single-choice',
            question: 'Which jQuery method is safe to use with user-provided content?',
            options: [
                { id: 'a', text: '.html(userContent)', isCorrect: false },
                { id: 'b', text: '.append("<p>" + userContent + "</p>")', isCorrect: false },
                { id: 'c', text: '.text(userContent)', isCorrect: true },
                { id: 'd', text: '$("<p>" + userContent + "</p>")', isCorrect: false },
            ],
            explanation: '.text() HTML-escapes content before inserting it, preventing XSS. .html(), .append(), and $() with string concatenation parse content as HTML, making them XSS vectors.',
            difficulty: 'medium', tags: ['jquery', 'security', 'xss'], points: 2,
        },
    ],
}

// ──────────────────────────────────────────────────
// Quiz generator
// ──────────────────────────────────────────────────

export function generateQuizForCourse(courseSlug: string): Quiz {
    const questions = QUESTION_BANKS[courseSlug] ?? getGenericQuestions(courseSlug)

    // Shuffle questions
    const shuffled = [...questions].sort(() => Math.random() - 0.5)

    return {
        id: `${courseSlug}-quiz-${Date.now()}`,
        courseSlug,
        title: `${courseSlug.charAt(0).toUpperCase() + courseSlug.slice(1)} Knowledge Check`,
        description: 'Test your understanding of the key concepts from this course.',
        questions: shuffled.slice(0, Math.min(10, shuffled.length)),
        passingScore: 70,
        shuffleQuestions: true,
        shuffleOptions: true,
        allowRetake: true,
        showExplanations: true,
        timeLimit: undefined,
    }
}

function getGenericQuestions(courseSlug: string): Question[] {
    return [
        {
            id: `${courseSlug}-g1`,
            type: 'true-false',
            question: `${courseSlug.toUpperCase()} knowledge is important for professional web development.`,
            answer: true,
            explanation: 'All technologies covered in this platform are used in professional web development environments.',
            difficulty: 'easy',
            tags: [courseSlug],
            points: 1,
        },
    ]
}